#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ARG PYTHON_VERSION=py39_4.11.0

ARG base_img
FROM $base_img

ARG PYTHON_VERSION
ENV PYTHON_VERSION=$PYTHON_VERSION

WORKDIR /

# Reset to root to run installation tasks
USER 0

RUN mkdir ${SPARK_HOME}/python
RUN apt-get install -y --no-install-recommends wget git apt-transport-https ca-certificates gnupg-agent apt-utils build-essential

COPY python/lib ${SPARK_HOME}/python/lib
ENV PYTHONPATH ${SPARK_HOME}/python/lib/pyspark.zip:${SPARK_HOME}/python/lib/py4j-*.zip

# Specify the User that the actual main process will run as
ARG spark_uid=185
USER ${spark_uid}

# Install Python
WORKDIR /

# install python
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${PYTHON_VERSION}-Linux-x86_64.sh -O miniconda.sh \
&& bash miniconda.sh -b -p miniconda

ENV PATH /miniconda/bin:$PATH

RUN git clone https://github.com/astrolabsoftware/fink-broker.git
RUN git clone https://github.com/astrolabsoftware/fink-docker.git

WORKDIR /fink-docker/centos9stream

RUN source ./install_python_deps.sh

ENV FINK_HOME /fink-broker
ENV PYTHONPATH $FINK_HOME:$PYTHONPATH
ENV PATH $FINK_HOME/bin:$PATH

WORKDIR /opt/spark/work-dir
ENTRYPOINT [ "/opt/entrypoint.sh" ]
