# Qserv operator CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Declare Version Variables
        id: vars
        shell: bash
        run: |
          echo "FINK_K8S_IMAGE=$(. ./conf.sh && echo $FINK_K8S_IMAGE)" >> $GITHUB_ENV
          echo "FINK_K8S_IMAGE=${FINK_K8S_IMAGE}"
      - name: Install pre-requisites (Spark)
        run: ./bin/prereq-install.sh
      - name: Build fink-k8s image
        run: |
          ./bin/docker-image-tool-fink.sh build
      - name: Export fink-k8s image
        run: |
          docker images
          echo "${{ env.FINK_K8S_IMAGE }}"
          mkdir -p artifacts
          docker save "${{ env.FINK_K8S_IMAGE }}" > artifacts/image.tar
          echo "${{ env.FINK_K8S_IMAGE }}" > artifacts/image-tag
      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: artifacts
  itest:
    name: Run integration tests
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Declare Version Variables
        id: vars
        shell: bash
        run: |
          echo "IMAGE=$(. ./conf.sh && echo $IMAGE)" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE}"
          echo "FINK_ALERT_SIMULATOR_DIR=$(. ./conf.sh && echo $FINK_ALERT_SIMULATOR_DIR)" >> $GITHUB_ENV
      - name: Clone fink-alert-simulator code
        run: ./bin/clone-fink-alert-simulator.sh
      - name: Create k8s/kind cluster
        run: |
          git clone --depth 1 -b "k8s-1.25.0" --single-branch https://github.com/k8s-school/kind-helper.git
          ./kind-helper/k8s-create.sh -s
      - name: Load fink-alert-simulator image inside kind
        run: |
          DIR="${{ env.FINK_ALERT_SIMULATOR_DIR }}"
          .  "${{ env.FINK_ALERT_SIMULATOR_DIR }}"/conf.sh
          if docker exec -t -- kind-control-plane crictl pull "$IMAGE"; then
            echo "::notice Succeeded to pull $IMAGE"
          else
            echo "::error Failed to pull $IMAGE"
          fi
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: docker-artifact
          path: artifacts
      - name: Load container image inside kind
        run: |
          kind load image-archive artifacts/image.tar
          docker exec -- kind-control-plane crictl image
      - name: Install fink-alert-simulator pre-requisites (argoCD)
        run: |
          "${{ env.FINK_ALERT_SIMULATOR_DIR }}"/prereq-install.sh
      - name: Install strimzi (kafka-operator)
        run: ./bin/strimzi-install.sh
      - name: Setup kafka
        run: ./bin/strimzi-setup.sh
      - name: Install fink-broker pre-requisites (Spark)
        run: ./bin/prereq-install.sh
      - name: Run fink-alert-simulator
        run: |
          "${{ env.FINK_ALERT_SIMULATOR_DIR }}"/argo-submit.sh
          argo watch @latest
      # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3
      - name: Run fink-broker
        run: |
          ./bin/itest.sh
  image-analysis:
    name: Analyze image
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: docker-artifact
          path: artifacts
      - name: Load image in local registry
        run: |
          docker load --input artifacts/image.tar
          echo "FINK_K8S_IMAGE=$(cat artifacts/artifacts/image-tag)" >> $GITHUB_ENV
      - name: Scan Fink image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "${{ env.FINK_K8S_IMAGE }}"
          fail-build: false
      - name: Display SARIF report
        run: |
          cat ${{ steps.scan.outputs.sarif }}
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
